spring.application.name=StaffProBackend
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=StaffProDB;encrypt=true;trustServerCertificate=true;

spring.datasource.username=mohit
spring.datasource.password=root


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
